### ISSUE TITLE
install Error

### ISSUE THREAD

**Issue by Ark-Chen** [jiangtao/webp-webpack-plugin#13]
## DESC
yarn add -D webp-webpack-plugin

### ENV

OS Platform:
macOS Big Sur 11.2

webpack Version:"webpack": "^3.6.0"

### error message
```
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-darwin-x64.tar.gz status code 403


ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-darwin-x64.tar.gz status code 403
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node/12.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/usr/local/Cellar/node/12.12.0/bin/node" "/usr/local/Cellar/node/12.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chenpeng/Desktop/webp/webp/node_modules/sharp
gyp ERR! node -v v12.12.0
```

**Comment by Ark-Chen** [comment]
Possible cause：https://github.com/lovell/sharp/issues/964
